### ISSUE TITLE
Steam - Failed to load steamui.so after latest Steam update (11/6/2024)

### ISSUE THREAD

**Issue by CalcProgrammer1** [ptitSeb/box86#1012]
After today's Steam update, Steam no longer starts on my Debian container install of box86/box64.  Opening Steam leads to symbol not found errors for posix_spawnattr_init and posix_spawnattr_destroy in libSDL3.so.0.

**Comment by ptitSeb** [comment]
Update both box86 and box64 and it should work again, I have pushed some fixes today.

**Comment by CalcProgrammer1** [comment]
I just saw that commit, I'm waiting for the debs to get updated and will try again (using ryanfortner repos).

**Comment by ptitSeb** [comment]
Ok.
It works on my side. Just box32 is still not working, and is hanging reaper now (I know what the issue is, but it will take some time to get a proprer fix). No issue if box64 is built without box32, wich should be the case for ryanfortner debs.

**Comment by StonedEdge** [comment]
> I built the latest box64/box86 (using ryanfortner deb workflow), and I no longer get the steamui.so error... however steam seems to return pretty quickly without actually initializing/doing anything:

```
retrolite@retro-lite-cm5:~/box86$ BOX86_SHOWSEGV=1 BOX86_LOG=1 steam
steam.sh[50268]: Running Steam on ubuntu 22.04 64-bit
steam.sh[50268]: STEAM_RUNTIME is enabled by the user
setup.sh[50332]: Steam runtime environment up-to-date!
/home/retrolite/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[50344]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[50268]: Couldn't find /home/retrolite/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[50268]: Can't find 'steam-runtime-check-requirements', continuing anyway
Debug level is 1
Show Segfault signal even if a signal handler is present
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Params database has 32 entries
Box86 with Dynarec v0.3.7 30c72e23 built on Nov  7 2024 10:32:59
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /home/retrolite/.local/share/Steam/ubuntu12_32/steam
steam detected
Apply RC params for steam
Applying BOX86_NOGTK=1
Applying BOX86_DYNAREC_STRONGMEM=1
Applying BOX86_DYNAREC_CALLRET=0
Applying BOX86_EMULATED_LIBS=libudev.so.0:libSDL2-2.0.so.0
Rename process to "steam"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libm.so.6
[2024-11-07 19:30:30] Startup - updater built Jul 16 2024 23:21:18
[2024-11-07 19:30:30] Startup - Steam Client launched with: '/home/retrolite/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
Using emulated /home/retrolite/.local/share/Steam/ubuntu12_32/crashhandler.so
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x6009aac0 (0x81b6)
11/07 19:30:30 minidumps folder is set to /tmp/dumps
11/07 19:30:30 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(50369)
50369|SIGSEGV @0xf753fd48 (???(0xf753fd48)) (x86pc=0x60023957/"/home/retrolite/.local/share/Steam/ubuntu12_32/crashhandler.so + 0x23957", esp=0xf6f5edc0, stack=0xf6765000:0xf6f65000 own=(nil) fp=0xf6f5f048), for accessing (nil) (code=1/prot=0), db=0xf5c613a0(0xf753fcd4:0xf753ff50/0x60023922:0x600239da//home/retrolite/.local/share/Steam/ubuntu12_32/crashhandler.so + 0x23922:clean, hash:d58a2ac1/d58a2ac1)
EAX:0x000000e0 ECX:0x0000001c EDX:0x00000000 EBX:0x6009aa58
ESP:0xf6f5edc0 EBP:0xf6f5f048 ESI:0x00000000 EDI:0xf6f5efbc
ESP-0x10:0xf6f5ee60 ESP-0x0c:0x00000000 ESP-0x08:0x600a1100 ESP-0x04:0x6009aa58
ESP+0x00:0x00000007 ESP+0x04:0xf6f5edd8 ESP+0x08:0x6009a2d0 ESP+0x0c:0x6009aa58
```

I too get the same error. Looks like crashhandler.so isn't being loaded correctly after the latest Steam update. Seems now that that library is required - I have flagged to ptitSeb. He is working on a fix soon after he is finished with box32 shenanigans :)

**Comment by StonedEdge** [comment]
> I built the latest box64/box86 (using ryanfortner deb workflow), and I no longer get the steamui.so error... however steam seems to return pretty quickly without actually initializing/doing anything:
> 
> 
> 
> ```
> 
> 📦[clayton@steam ~]$ STEAMOS=1 STEAM_RUNTIME=1 DBUS_FATAL_WARNINGS=0 steam
> 
> steam.sh[9949]: Running Steam on debian 12 64-bit
> 
> steam.sh[9949]: STEAM_RUNTIME is enabled by the user
> 
> setup.sh[10013]: Steam runtime environment up-to-date!
> 
> /home/clayton/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
> 
> run.sh[10025]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
> 
> steam.sh[9949]: Couldn't find /home/clayton/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
> 
> steam.sh[9949]: Can't find 'steam-runtime-check-requirements', continuing anyway
> 
> Box86 with Dynarec v0.3.7 450347f0 built on Nov  7 2024 07:23:46
> 
> [2024-11-07 00:07:42] Startup - updater built Jul 16 2024 23:21:18
> 
> [2024-11-07 00:07:42] Startup - Steam Client launched with: '/home/clayton/.local/share/Steam/ubuntu12_32/steam'
> 
> ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
> 
> src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
> 
> src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
> 
> 11/07 00:07:42 minidumps folder is set to /tmp/dumps
> 
> 11/07 00:07:42 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(10044)
> 
> 📦[clayton@steam ~]$ 
> 
> ```
> 
> 

Hmm, so I still can't get this working yet.

**Comment by ptitSeb** [comment]
I have pushed some update to box86 (and box64 too). I was reproducing the issue on my Rock5B, and it's fixed now. So hopefully, it's fixed for everyone

**Comment by StonedEdge** [comment]
Unfortunately it seems to still be broken for me:

` retrolite@retro-lite-cm5:~$ steam
steam.sh[12690]: Running Steam on ubuntu 22.04 64-bit
steam.sh[12690]: STEAM_RUNTIME is enabled by the user
setup.sh[12754]: Steam runtime environment up-to-date!
/home/retrolite/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[12766]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[12690]: Couldn't find /home/retrolite/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[12690]: Can't find 'steam-runtime-check-requirements', continuing anyway
Box86 with Dynarec v0.3.7 4caece4c built on Nov  9 2024 11:30:46
[2024-11-09 17:13:38] Startup - updater built Jul 16 2024 23:21:18
[2024-11-09 17:13:38] Startup - Steam Client launched with: '/home/retrolite/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
11/09 17:13:38 minidumps folder is set to /tmp/dumps
11/09 17:13:38 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(12791)
retrolite@retro-lite-cm5:~$ Box86 with Dynarec v0.3.7 4caece4c built on Nov  9 2024 11:30:46
/.local/share/Steam/linux32/steamerrorreporter[12802]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241109171338_3.dmp
/.local/share/Steam/linux32/steamerrorreporter[12802]: Finished uploading minidump (out-of-process): success = yes
/.local/share/Steam/linux32/steamerrorreporter[12802]: response: CrashID=bp-c8c3115d-9320-44e6-a470-815f42241109
/.local/share/Steam/linux32/steamerrorreporter[12802]: file ''/tmp/dumps/assert_20241109171338_3.dmp'', upload yes: ''CrashID=bp-c8c3115d-9320-44e6-a470-815f42241109''`

**Comment by ptitSeb** [comment]
that's really strange. For me it just segfault very quickly if crashhandler is not present.

**Comment by StefanW1357** [comment]
I now have Steam running on my Raspberry Pi5 (with custom 4k page size kernel) which is great, but still having issues running on my Rock5B, but that seems to library problems. 

I think the SteamUI issue is resolved, but the issues that @StonedEdge has been is reporting, is from a new install? (correct me if you've had steam running and updated recently). 

Steps to reproduce crash when running steam for the first time:
First move a working copy if there is one:
```
mv -v ~/.local/share/Steam/ ~/Steam_working_backup
renamed '/home/stefan/.local/share/Steam/' -> '/home/stefan/Steam_working_backup'
```

Now try running steam (after using the install_steam.sh script)

```
stefan@raspberrypi:~ $ steam
bin_steam.sh[35957]: Setting up Steam content in /home/stefan/.local/share/Steam
steam.sh[35957]: Running Steam on debian 12 64-bit
steam.sh[35957]: STEAM_RUNTIME is enabled by the user
setup.sh[36030]: Updating Steam runtime environment...
/home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[43050]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[35957]: Couldn't find /home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[35957]: Can't find 'steam-runtime-check-requirements', continuing anyway
Box86 with Dynarec v0.3.7 1e749beb built on Nov  9 2024 11:30:12
[2024-11-09 16:02:18] Startup - updater built Jul 16 2024 23:21:18
[2024-11-09 16:02:18] Startup - Steam Client launched with: '/home/stefan/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
11/09 16:02:18 minidumps folder is set to /tmp/dumps
11/09 16:02:18 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(43072)
Box86 with Dynarec v0.3.7 1e749beb built on Nov  9 2024 11:30:12
ocal/share/Steam/linux32/steamerrorreporter[43083]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241109160218_3.dmp
stefan@raspberrypi:~ $ ocal/share/Steam/linux32/steamerrorreporter[43083]: Finished uploading minidump (out-of-process): success = yes
ocal/share/Steam/linux32/steamerrorreporter[43083]: response: CrashID=bp-3be923fb-f0b2-4984-8907-2a7962241109
ocal/share/Steam/linux32/steamerrorreporter[43083]: file ''/tmp/dumps/assert_20241109160218_3.dmp'', upload yes: ''CrashID=bp-3be923fb-f0b2-4984-8907-2a7962241109''
```
Now run again with the new BOX86_NOCRASHHANDLER flag 

```
stefan@raspberrypi:~ $ BOX86_NOCRASHHANDLER=1 BOX86_LOG=1 steam
steam.sh[43086]: Running Steam on debian 12 64-bit
steam.sh[43086]: STEAM_RUNTIME is enabled by the user
setup.sh[43150]: Steam runtime environment up-to-date!
/home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[43162]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[43086]: Couldn't find /home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[43086]: Can't find 'steam-runtime-check-requirements', continuing anyway
Debug level is 1
Box86 will consider crashhnadler.so to not be present
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Cortex-A76 with 4 Cores
Params database has 32 entries
Box86 with Dynarec v0.3.7 1e749beb built on Nov  9 2024 11:30:12
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 78 Env var
Looking for /home/stefan/.local/share/Steam/ubuntu12_32/steam
steam detected
Apply RC params for steam
Applying BOX86_NOGTK=1
Applying BOX86_DYNAREC_STRONGMEM=1
Applying BOX86_DYNAREC_CALLRET=0
Applying BOX86_EMULATED_LIBS=libudev.so.0:libSDL2-2.0.so.0
Rename process to "steam"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libm.so.6
[2024-11-09 16:02:43] Startup - updater built Jul 16 2024 23:21:18
[2024-11-09 16:02:43] Startup - Steam Client launched with: '/home/stefan/.local/share/Steam/ubuntu12_32/steam'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1467) : BFileExists( m_FontFileLight )
src/steamexe/updateui_xwin.cpp (1467) : BFileExists( m_FontFileLight )
Using native(wrapped) libGL.so.1
[2024-11-09 16:02:44] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2024-11-09 16:02:44] Using the following download hosts for Public, Realm steamglobal
[2024-11-09 16:02:44] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-11-09 16:02:44] Verifying installation...
[2024-11-09 16:02:44] Unable to read and verify install manifest /home/stefan/.local/share/Steam/package/steam_client_ubuntu12.installed
[2024-11-09 16:02:44] Verification complete
[2024-11-09 16:02:44] Downloading Update...
[2024-11-09 16:02:44] Checking for available update...
[2024-11-09 16:02:44] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2024-11-09 16:02:44] Manifest download: send request
[2024-11-09 16:02:44] Manifest download: waiting for download to finish
[2024-11-09 16:02:45] Manifest download: finished
[2024-11-09 16:02:45] Downloaded new manifest: /client/steam_client_ubuntu12 version 1730853027, installed version 0, existing pending version 0
[2024-11-09 16:02:45] Package file tenfoot_images_all.zip.vz.193cb8c4eb4446698ea2c0a9e8c4e6b6a623dac7_5572671 missing or incorrect size
[2024-11-09 16:02:45] Package file steamui_websrc_all.zip.vz.dabd145d9c4292ce172892fa7c11757eca2c6015_24841146 missing or incorrect size
[2024-11-09 16:02:45] Package file resources_misc_all.zip.vz.e86a975545f3ab21a77373870cb311ef93934b8c_2224876 missing or incorrect size
[2024-11-09 16:02:45] Package file resources_hidpi_all.zip.vz.3de815c3117712cb9eeb7ea4c8b275faf481dcfd_56342 missing or incorrect size
[2024-11-09 16:02:45] Package file resources_all.zip.vz.3c8b3203e5c69d75ea0684c2409b86fe4d0d6f83_2856188 missing or incorrect size
[2024-11-09 16:02:45] Package file strings_en_all.zip.147798246441b35c9a4dbdeecef8d6c4ffda4346 missing or incorrect size
[2024-11-09 16:02:45] Package file strings_all.zip.vz.e7d4ab28d5506fe9ee3667bd38e0764a03774b4e_2007131 missing or incorrect size
[2024-11-09 16:02:45] Package file public_all.zip.vz.9278fb89cc7d24f86341f1398ae3c7d578e4148c_23328700 missing or incorrect size
[2024-11-09 16:02:45] Package file steamui_websrc_sounds_all.zip.vz.a2b25775b33d943e54c45d176558de379111ef5f_3220470 missing or incorrect size
[2024-11-09 16:02:45] Package file steamui_websrc_movies_all.zip.4d2183b0476852dfb695b8d70192a0ccece8c7d0 missing or incorrect size
[2024-11-09 16:02:45] Package file bins_ubuntu12.zip.vz.4e8f721765dd61533b2e1ff86d75602ade45bb80_29947909 missing or incorrect size
[2024-11-09 16:02:45] Package file bins_sdk_ubuntu12.zip.vz.e8786d9695253dccc58d41d6c06240cba9e55e2e_19089160 missing or incorrect size
[2024-11-09 16:02:45] Package file bins_codecs_ubuntu12.zip.vz.559e65ef71ebc044f29071dbebee20785daaa46c_12204977 missing or incorrect size
[2024-11-09 16:02:45] Package file bins_misc_ubuntu12.zip.vz.702b702a03e1476126bb70ce80e33ea73f5aa215_18275764 missing or incorrect size
[2024-11-09 16:02:45] Package file webkit_ubuntu12.zip.vz.4f1b73b22033a1c01e04f6a901116d14e1d6a881_89938579 missing or incorrect size
[2024-11-09 16:02:45] Package file miles_ubuntu12.zip.vz.5093ef941e6e5195a60ab3259077694dec994016_295496 missing or incorrect size
[2024-11-09 16:02:45] Package file sdl3_ubuntu12.zip.vz.52a134ab49559c6e716af77c9ee9738136232149_6305794 missing or incorrect size
[2024-11-09 16:02:45] Package file steam_ubuntu12.zip.vz.23b30c489a4d81cb37204d90433b585056684ed7_2621111 missing or incorrect size
[2024-11-09 16:02:45] Package file runtime_scout_ubuntu12.zip.594c28f2cb961e3fc891e817a699f010b002da98 missing or incorrect size
[2024-11-09 16:02:45] Package file runtime_sniper_ubuntu12.zip.6f95df8c94a3dfd945bf2b5cc0b0e16318d3899e missing or incorrect size
...
```
Note this is long and so I have truncated this as the steam client installer downloads and installs the client. 

However, while the new flag does allow steam to update, it then breaks when trying to start:
```

...
Steam logging initialized: directory: /home/stefan/.local/share/Steam/logs

Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/gio/modules/libdconfsettings.so
Using native(wrapped) libdbus-1.so.3
Error initializing native libudev.so.1 (last dlerror is libudev.so.1: wrong ELF class: ELFCLASS64)
Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu/libudev.so.1
Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/filesystem_stdio.so
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x69809af4 (0x61a6)
Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/vgui2_s.so
Using native(wrapped) libopenal.so.1
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x69972b08 (0xe3c6)
Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/chromehtml.so
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x69bf39a0 (0x16206)
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0x40180080
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0x40180090
Using native(wrapped) libXss.so.1
Error initializing native libvulkan.so.1 (last dlerror is libvulkan.so.1: wrong ELF class: ELFCLASS64)
Using emulated /home/stefan/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu/libvulkan.so.1
Using native(wrapped) libXss.so.1
44006|SIGSEGV @0xf7d27e10 (strlen (/lib/arm-linux-gnueabihf/libc.so.6)) (x86pc=0x4004059b/"???", esp=0xf724c4ec, stack=0xf6a55000:0xf7255000 own=(nil) fp=(n
il)), for accessing (nil) (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0)
ESP-0x10:0x69bf3924 ESP-0x0c:0x69bf6644 ESP-0x08:0x671b7030 ESP-0x04:0x00000000
ESP+0x00:0x699a25f6 ESP+0x04:0x00000000 ESP+0x08:0x0000003c ESP+0x0c:0x671b7760
44006|Double SIGSEGV (code=1, pc=0xf7d27e10, addr=(nil))!
src/common/framefunction.cpp (238) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[Bootstrapper HTTP Client] still regis
tered
src/common/framefunction.cpp (238) : Assertion Failed: CFrameFunctionMgr::~CFrameFunctionMgr: non static FrameFunction[Bootstrapper HTTP Client] still regis
tered
```
Running steam again without the new flag continues to run and allows the login screen to be shown. I thought this observation might help others.

**Comment by CalcProgrammer1** [comment]
I updated my Debian container on my OnePlus 6T and Steam is working again (using the latest ryanfortner debs).

**Comment by CalcProgrammer1** [comment]
![image](https://github.com/user-attachments/assets/a6956186-ca0e-4d9a-b73c-e00bf08c500c)

Closing as Steam is working for me.
