### ISSUE TITLE
gmod server on rpi4

### ISSUE THREAD

**Issue by Blaubeeree** [ptitSeb/box86#138]
I'm trying to run a Garrys Mod server on my Raspberry Pi 4 (8GB RAM) with Box86. When I try to start the sever I'm getting many errors that some functions in libm.so.6 are missing.

Log: https://hastebin.com/asoduqaxon.rb

**Comment by ptitSeb** [comment]
And then it crash?

Those symbol are missing from system libm, that's unfortunate. I can do a workaround, I'll check that later.

**Comment by tmvkrpxl0** [comment]
Try finding libraries using "find ~/.local/share/" -name "libtinfo*"
then it'll say some 32bit libraries are under ubuntu32_64 directory, which is part of steamcmd
sorry that i can't remember the exact directory name.
I solved my problems using libraries that is installed by steamcmd automatically.
I'm not sure if this gonna work for you, but give it a try

**Comment by ptitSeb** [comment]
I have wrapped libncurses now, so the lib not found should be fixed now.

**Comment by tmvkrpxl0** [comment]
update:exact path is this: `~/.local/share/Steam/ubuntu12_32`
there should be some libraries. and under `~/.local/share/Steam/ubuntu12_32/steam-runtime`, there should be folders called i386, usr, lib, etc.. those folders contain libraries

**Comment by Blaubeeree** [comment]
@tmvkrpxl0 I dont have a `~/.local/share/Steam` folder. Maybe because I installed it manually and not with `sudo apt install`. I searched for libraries in the folder where I installed steamcmd, there were a few but not that one i need.

@ptitSeb I'll reinstall box86 and try it again witch the new version in the next few days.

**Comment by tmvkrpxl0** [comment]
@Blaubeeree I installed manually and it was there. i don't know why it isn't there.

**Comment by Blaubeeree** [comment]
I still get the same errors. 
Log: https://hastebin.com/wihayanipo.rb

**Comment by ptitSeb** [comment]
Ok @Blaubeeree , I have just pushed some workaround. Now the all the missing "__xxx_finite" message should be gone.

**Comment by Blaubeeree** [comment]
Now I get many warnings saying `Cannot dlopen` and a warning `Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.`. In the end it crash (`Segmentation fault (core dumped)`).

Log: https://hastebin.com/afojazevej.sql

**Comment by ptitSeb** [comment]
Two different things.
tsinfo and ncurses are wrapped, so they should load correctly now. Unless it's not installed (try `sudo apt install libncurses` maybe) or it use one of the few funciton still not wrapped (use `BOX86_DLSYM_ERROR=1` to see the dlsym call).

all the dlopen fillure are not really box86 fault. The file is probably not there or something like that, and so the openning fail. Does one of the `.so` file is looking for exist?

**Comment by Blaubeeree** [comment]
libncurses and libtinfo are installed. The `.so` files are missing. I'll try a few things (maybe reinstall everything) and let you know if I find something. If u have any idea what i can try pls let me know. But thanks for your help so far.

**Comment by Blaubeeree** [comment]
In the loast days I had finally time to test a bit. I didn't managed to get the server working, but since it isn't a issue of box86 I'll close this issue.
