### ISSUE TITLE
Box86 on arm64

### ISSUE THREAD

**Issue by wormstest** [ptitSeb/box86#565]
Hello, i running proot Debian with hardware acceleration (Turnip Zink) and want to run box86 without changing termux and Debian to armhf, is that possible?

**Comment by ptitSeb** [comment]
No, it's not possible. Box86 requires a 32bits subsytem to run on.

**Comment by WheezyE** [comment]
I’m not sure if @wormstest meant to ask if running box86 with multiarch on aarch64 proot (Termux) was possible.  But if that is what they meant to ask, then I’ve got an aarch64/multiarch proot available here to test: https://github.com/lowspecman420/AnBox86

**Comment by wormstest** [comment]
I need box86 already in proot installed system. Not realizing that the script is for termux, I broke apt update, because the repositories from termux are trying to install on Debian

**Comment by WheezyE** [comment]
Ah yeah, that makes sense. Yes, this script installs a new proot into Termux and then installs box86/box64 into that proot using multiarch. Sorry about that! 😅

Feel free to copy any code from that script if it helps.

**Comment by wormstest** [comment]
Now my repositories are broken, and they try to install even when they are not in sources.list
```
root@localhost:~# apt-get update                                      Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:5 https://termux.mentality.rip/termux-games games InRelease [7999 B]
Get:6 https://termux.mentality.rip/termux-science science InRelease [8011 B]
Err:5 https://termux.mentality.rip/termux-games games InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
Err:6 https://termux.mentality.rip/termux-science science InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
Reading package lists... Done
W: GPG error: https://termux.mentality.rip/termux-games games InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
E: The repository 'https://termux.mentality.rip/termux-games games InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://termux.mentality.rip/termux-science science InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
E: The repository 'https://termux.mentality.rip/termux-science science InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by WheezyE** [comment]
You'll have to remove the Termux repo's manually with `sudo nano $PREFIX/etc/apt/sources.list`

**Comment by wormstest** [comment]
You misunderstood me, I have this error in Debian proot, but there are no repositories in sources.list Termux.

**Comment by wormstest** [comment]
My sources.list:
`GNU nano 6.0                                            /etc/apt/sources.list
deb http://deb.debian.org/debian bullseye main contrib non-free
deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb http://deb.debian.org/debian bullseye-backports main contrib non-free
deb http://security.debian.org/debian-security/ bullseye-security main contrib`
Log apt update:
`root@localhost:~# apt-get update
Hit:1 http://deb.debian.org/debian bullseye InRelease
Hit:2 http://deb.debian.org/debian bullseye-updates InRelease
Hit:3 http://deb.debian.org/debian bullseye-backports InRelease
Get:4 https://termux.mentality.rip/termux-games games InRelease [7999 B]
Get:5 https://termux.mentality.rip/termux-science science InRelease [8011 B]
Hit:6 http://security.debian.org/debian-security bullseye-security InRelease
Err:4 https://termux.mentality.rip/termux-games games InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
Err:5 https://termux.mentality.rip/termux-science science InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
Reading package lists... Done
W: GPG error: https://termux.mentality.rip/termux-games games InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
E: The repository 'https://termux.mentality.rip/termux-games games InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://termux.mentality.rip/termux-science science InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5A897D96E57CF20C
E: The repository 'https://termux.mentality.rip/termux-science science InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by wormstest** [comment]
Okay i fixed, return to the question about box86, which can not be launched directly without changing the system, or can I install packages from armhf?

**Comment by WheezyE** [comment]
The [methods outlined in AnBox86_64.sh](https://github.com/lowspecman420/AnBox86/blob/737568e1c578e2372dd48e42fa8b187e6217ac92/AnBox86_64.sh#L62) are the only way I know of getting a multiarch:armhf aarch64 proot working with box86, though I'm still not sure if that's your goal.  Feel free to peek at that code if it helps - and best of luck!

**Comment by wormstest** [comment]
I running on arm64, and have error OpenGL, host in have Adreno 640 GPU access
![Uploading Screenshot_2022-02-04-08-02-59-087_com.termux.x11.jpg…]()

**Comment by wormstest** [comment]
I running on arm64 wihout resinstall system to armhf

**Comment by arturi** [comment]
@ptitSeb Sorry, I still have this confused in my head. 

>  Box86 requires a 32bits subsytem to run on.

Can I run Wine and 32bit games on Raspberry Pi OS 64, does it have 32bits subsytem? If not, this means it’s best to stick to a 32bit OS for Raspberry Pi retro gamers. But then some newer games/apps are 64bit 🤔

**Comment by arturi** [comment]
@ptitSeb thanks! Ok, so I install this, and then box86 (which PiApps disallows currently on 64bit), and then hopefully Wine.
